// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedBlob: typeof import('./src/components/animations/AnimatedBlob.vue')['default']
    AnimatedCheckIcon: typeof import('./src/components/animations/AnimatedCheckIcon.vue')['default']
    AnimatedLoadingBar: typeof import('./src/components/animations/AnimatedLoadingBar.vue')['default']
    ArrowLongDownSolidIcon: typeof import('@heroicons/vue/24/solid')['ArrowLongDownIcon']
    ArrowLongUpSolidIcon: typeof import('@heroicons/vue/24/solid')['ArrowLongUpIcon']
    AwsApiGatewayIcon: typeof import('./src/components/icons/AwsApiGatewayIcon.vue')['default']
    AwsDynamoDbIcon: typeof import('./src/components/icons/AwsDynamoDbIcon.vue')['default']
    AwsLambdaIcon: typeof import('./src/components/icons/AwsLambdaIcon.vue')['default']
    DataTable: typeof import('./src/components/tables/DataTable.vue')['default']
    IconContainer: typeof import('./src/components/containers/IconContainer.vue')['default']
    LayerPanel: typeof import('./src/components/layers/LayerPanel.vue')['default']
    LPContentForApplicationLogic: typeof import('./src/pages/skills-ddd-page/skills-ddd/components/layer-panels/LPContentForApplicationLogic.vue')['default']
    LPContentForDataAccess: typeof import('./src/pages/skills-ddd-page/skills-ddd/components/layer-panels/LPContentForDataAccess.vue')['default']
    LPContentForDomainLogic: typeof import('./src/pages/skills-ddd-page/skills-ddd/components/layer-panels/LPContentForDomainLogic.vue')['default']
    MinusSolidIcon: typeof import('@heroicons/vue/24/solid')['MinusIcon']
    MultiLayerPanel: typeof import('./src/components/layers/MultiLayerPanel.vue')['default']
    MultiTabbedDocument: typeof import('./src/components/tabs/MultiTabbedDocument.vue')['default']
    Navbar: typeof import('./src/pages/components/Navbar.vue')['default']
    Page: typeof import('./src/pages/Page.vue')['default']
    PanelFile: typeof import('./src/pages/skills-tests-page/skills-tests/components/PanelFile.vue')['default']
    PanelTests: typeof import('./src/pages/skills-tests-page/skills-tests/components/PanelTests.vue')['default']
    PlusSolidIcon: typeof import('@heroicons/vue/24/solid')['PlusIcon']
    PortfolioPage: typeof import('./src/pages/portfolio-page/PortfolioPage.vue')['default']
    QueryBuilder: typeof import('./src/components/query-building/QueryBuilder.vue')['default']
    RestEndpoint: typeof import('./src/pages/skills-rest-page/skills-rest/components/RestEndpoint.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsAws: typeof import('./src/pages/skills-aws-page/skills-aws/SkillsAws.vue')['default']
    SkillsDDD: typeof import('./src/pages/skills-ddd-page/skills-ddd/SkillsDDD.vue')['default']
    SkillsDDDPage: typeof import('./src/pages/skills-ddd-page/SkillsDDDPage.vue')['default']
    SkillsDotnet: typeof import('./src/pages/skills-dotnet-page/skills-dotnet/SkillsDotnet.vue')['default']
    SkillsDotnetPage: typeof import('./src/pages/skills-dotnet-page/SkillsDotnetPage.vue')['default']
    SkillsFrontend: typeof import('./src/pages/skills-frontend-page/skills-frontend/SkillsFrontend.vue')['default']
    SkillsFrontendPage: typeof import('./src/pages/skills-frontend-page/SkillsFrontendPage.vue')['default']
    SkillsGit: typeof import('./src/pages/skills-git-page/skills-git/SkillsGit.vue')['default']
    SkillsGitPage: typeof import('./src/pages/skills-git-page/SkillsGitPage.vue')['default']
    SkillsMessaging: typeof import('./src/pages/skills-message-page/skills-messaging/SkillsMessaging.vue')['default']
    SkillsMonoliths: typeof import('./src/pages/skills-monoliths-page/skills-monoliths/SkillsMonoliths.vue')['default']
    SkillsRest: typeof import('./src/pages/skills-rest-page/skills-rest/SkillsRest.vue')['default']
    SkillsRestPage: typeof import('./src/pages/skills-rest-page/SkillsRestPage.vue')['default']
    SkillsTests: typeof import('./src/pages/skills-tests-page/skills-tests/SkillsTests.vue')['default']
    SkillsTestsPage: typeof import('./src/pages/skills-tests-page/SkillsTestsPage.vue')['default']
    TabbedDocument: typeof import('./src/components/tabs/TabbedDocument.vue')['default']
    TestExample: typeof import('./src/pages/skills-tests-page/skills-tests/components/TestExample.vue')['default']
  }
}
