// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedBlob: typeof import('./src/components/animations/AnimatedBlob.vue')['default']
    AnimatedCheckIcon: typeof import('./src/components/animations/AnimatedCheckIcon.vue')['default']
    AnimatedLoadingBar: typeof import('./src/components/animations/AnimatedLoadingBar.vue')['default']
    AwsApiGatewayIcon: typeof import('./src/components/icons/AwsApiGatewayIcon.vue')['default']
    AwsDynamoDbIcon: typeof import('./src/components/icons/AwsDynamoDbIcon.vue')['default']
    AwsLambdaIcon: typeof import('./src/components/icons/AwsLambdaIcon.vue')['default']
    IconContainer: typeof import('./src/components/containers/IconContainer.vue')['default']
    LayerPanel: typeof import('./src/components/layers/LayerPanel.vue')['default']
    LayerPanelApplicationLogic: typeof import('./src/pages/portfolio-page/skills-ddd/components/LayerPanelApplicationLogic.vue')['default']
    LayerPanelDataAccess: typeof import('./src/pages/portfolio-page/skills-ddd/components/LayerPanelDataAccess.vue')['default']
    LayerPanelDomainLogic: typeof import('./src/pages/portfolio-page/skills-ddd/components/LayerPanelDomainLogic.vue')['default']
    LPContentForApplicationLogic: typeof import('./src/pages/portfolio-page/skills-ddd/components/layer-panels/LPContentForApplicationLogic.vue')['default']
    LPContentForDataAccess: typeof import('./src/pages/portfolio-page/skills-ddd/components/layer-panels/LPContentForDataAccess.vue')['default']
    LPContentForDomainLogic: typeof import('./src/pages/portfolio-page/skills-ddd/components/layer-panels/LPContentForDomainLogic.vue')['default']
    MultiLayerPanel: typeof import('./src/components/layers/MultiLayerPanel.vue')['default']
    PanelFile: typeof import('./src/pages/portfolio-page/skills-tests/components/PanelFile.vue')['default']
    PanelTests: typeof import('./src/pages/portfolio-page/skills-tests/components/PanelTests.vue')['default']
    PortfolioPage: typeof import('./src/pages/portfolio-page/PortfolioPage.vue')['default']
    RestEndpoint: typeof import('./src/pages/portfolio-page/skills-rest/components/RestEndpoint.vue')['default']
    SkillsAws: typeof import('./src/pages/portfolio-page/skills-aws/SkillsAws.vue')['default']
    SkillsDDD: typeof import('./src/pages/portfolio-page/skills-ddd/SkillsDDD.vue')['default']
    SkillsDotnet: typeof import('./src/pages/portfolio-page/skills-dotnet/SkillsDotnet.vue')['default']
    SkillsFrontend: typeof import('./src/pages/portfolio-page/skills-frontend/SkillsFrontend.vue')['default']
    SkillsGit: typeof import('./src/pages/portfolio-page/skills-git/SkillsGit.vue')['default']
    SkillsMessaging: typeof import('./src/pages/portfolio-page/skills-messaging/SkillsMessaging.vue')['default']
    SkillsMonoliths: typeof import('./src/pages/portfolio-page/skills-monoliths/SkillsMonoliths.vue')['default']
    SkillsRest: typeof import('./src/pages/portfolio-page/skills-rest/SkillsRest.vue')['default']
    SkillsTests: typeof import('./src/pages/portfolio-page/skills-tests/SkillsTests.vue')['default']
    TestExample: typeof import('./src/pages/portfolio-page/skills-tests/components/TestExample.vue')['default']
  }
}
