name: Build / Run Tests

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Rush Test
        run: node common/scripts/install-run-rush.js test:nowatch
